Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -158,10 +158,11 @@ phases:
 
       - echo "Retrieving GitHub token from Secrets Manager"
       - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id LLApplicationToken --query SecretString --output text | jq -r .GITHUB_TOKEN)
-      - if [ -z "$GITHUB_TOKEN" ]; then
-        echo "Failed to retrieve GitHub token.";
-        exit 1;
-      fi
+      - |
+        if [ -z "$GITHUB_TOKEN" ]; then
+          echo "Failed to retrieve GitHub token."
+          exit 1
+        fi
 
       - echo "Logging in to GitHub Container Registry"
       - echo $GITHUB_TOKEN | docker login ghcr.io -u sabbasani259 --password-stdin
