Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -151,16 +151,27 @@ phases:
 
   post_build:
     commands:
+      - echo "Downloading EAR file from S3 bucket..."
+      - mkdir -p build/ear
+      - aws s3 cp s3://buildartif/wise.ear build/ear/wise.ear
+      - ls -l build/ear/wise.ear
+
       - echo "Retrieving GitHub token from Secrets Manager"
       - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id LLApplicationToken --query SecretString --output text | jq -r .GITHUB_TOKEN)
       - if [ -z "$GITHUB_TOKEN" ]; then
-          echo "Failed to retrieve GitHub token.";
-          exit 1;
-        fi
+        echo "Failed to retrieve GitHub token.";
+        exit 1;
+      fi
+
       - echo "Logging in to GitHub Container Registry"
       - echo $GITHUB_TOKEN | docker login ghcr.io -u sabbasani259 --password-stdin
-      - docker build -t ghcr.io/sabbasani259/wise-ear:latest .
+
+      - echo "Building Docker image with the EAR file..."
+      - docker build -t ghcr.io/sabbasani259/wise-ear:latest --build-arg EAR_FILE=build/ear/wise.ear -f docker/Dockerfile .
+
+      - echo "Pushing Docker image to GHCR..."
       - docker push ghcr.io/sabbasani259/wise-ear:latest
+
       - echo "Docker image pushed to GHCR."
 
 artifacts:
