Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -25,8 +25,13 @@ phases:
       - wget https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar -O lib/log4j-api-2.20.0.jar
 
       # Hibernate
+      # Copy the reverseGeocoding.jar to the lib directory
       - cp hibernate-c3p0-4.1.1.Final.jar lib/hibernate-c3p0-4.1.1.Final.jar
+
+      # Verify the contents of the JAR file
       - jar tf lib/hibernate-c3p0-4.1.1.Final.jar
+
+      #- wget https://repo1.maven.org/maven2/org/hibernate/hibernate-core/5.6.15.Final/hibernate-core-5.6.15.Final.jar -O lib/hibernate-core-5.6.15.Final.jar
 
       # JSON libraries
       - wget https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar -O lib/json-simple-1.1.1.jar
@@ -133,6 +138,9 @@ phases:
       # Add Hibernate Core (if using Hibernate)
       - wget https://repo1.maven.org/maven2/org/hibernate/hibernate-core/3.6.10.Final/hibernate-core-3.6.10.Final.jar -O lib/hibernate-core-3.6.10.Final.jar
 
+      # NominatimReverseGeocoding JAPI
+      # - wget https://repo1.maven.org/maven2/eu/bitm/NominatimReverseGeocoding/1.0/NominatimReverseGeocoding-1.0.jar -O lib/NominatimReverseGeocoding-1.0.jar
+
       # Compile with all dependencies
       - find src -name "*.java" > sources.txt
       - cat sources.txt
@@ -162,10 +170,10 @@ phases:
       - echo "Retrieving GitHub token from Secrets Manager"
       - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id LLApplicationToken --query SecretString --output text | jq -r .GITHUB_TOKEN)
       - |
-        if [ -z "$GITHUB_TOKEN" ]; then
-          echo "Failed to retrieve GitHub token."
-          exit 1
-        fi
+      if [ -z "$GITHUB_TOKEN" ]; then
+        echo "Failed to retrieve GitHub token."
+        exit 1
+      fi
 
       - echo "Logging in to GitHub Container Registry"
       - echo $GITHUB_TOKEN | docker login ghcr.io -u sabbasani259 --password-stdin
